### ISSUE TITLE
Make bakery pipeline.yml a generated file

### ISSUE THREAD

**Issue by tomjw64** [openstax/concourse-pipelines#17]

**Comment by brittweinstein** [comment]
@tomjw64 please resolve conflicts and we can merge the associated PR :)

**Comment by omehes** [comment]
@brittweinstein @tomjw64 Any steps as how to test this? Is this testable by me?

**Comment by tomjw64** [comment]
Through an unfortunate series of events this has already gone into production cops. We need to ensure the output we are getting from cops.openstax.org is good.

**Comment by omehes** [comment]
@tomjw64 Thanks :) In that case I am already testing it by creating jobs and checking pdfs.

**Comment by omehes** [comment]
pdfs look good, the collated chapter numbering is correct now

![chap_no](https://user-images.githubusercontent.com/44207656/73566327-37477800-4429-11ea-8f92-01fcbfaab65e.png)

![chapt_no33](https://user-images.githubusercontent.com/44207656/73566335-3d3d5900-4429-11ea-824b-9e25790dad3c.png)
